package com.winit.baskinrobbin.salesman.common;
/**
 * this class will have some constant values to make differentiate the different different conditions
 */
public enum CONSTANTOBJ
{
	PRINT_VERIFY_ITEMS_IN_VEHICLE,
	PRINT_VERIFY_STOCK_UNLOAD,
	PRINT_SALES,
	PAYMENT_RECEIPT,
	PAYMENT_INVOICE_RECEIPT,
	PRINT_SALES_RETURN,
	PRINT_SALES_REPLACE,
	PRINT_SALES_REPLACE_SUMMARY,
	NEW_CUSTOMER,
	ORDER_SUMMARY,
	PAYMENT_SUMMARY,
	PRINT_EOT_SUMMARY,
	TRANSFER_IN,
	TRANSFER_OUT,
	PRINT_FREEDELIVERY,
	PRINT_RETURN_INVENTORY,
	PRINT_INVENTORY,
	PRINT_LOAD_REQUEST,
	LPO_DELIVERY_NOTE,
	LPO_DELIVERY_NOTE_SUMMARY,
	PAYMENT_SEP_SUMMARY
	//	--------------------------------------------
	,PRINT_VERIFY_INVENTOTY
}
